name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        cache: 'pip'
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile script/main.py

    - name: Upload executable
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/main # Windows executable

    - name: Upload executable
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: linux-executable
        path: dist/main  # Linux executable (no extension)

    - name: Upload executable
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v2
      with:
        name: macos-executable
        path: dist/main  # macOS executable (no extension)

