name: Build Ubuntu Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # ou macos-latest si tu travailles sur macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile script/main.py  # Remplace par le chemin de ton fichier principal

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-executable  # ou macos-executable si sur macOS
        path: dist/main  # Remplace 'main' par le nom de l'exécutable généré
